apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-deployment
  minReplicas: 3
  maxReplicas: 21
  targetCPUUtilizationPercentage: 50
